import {randomUUID, randomBytes, scryptSync, timingSafeEqual} from 'node:crypto';
export const id=()=>randomUUID();
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Cuiaba',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function fail(message,status=400){const e=new Error(message);e.status=status;throw e;}
export function text(v,name,required=true){let s=String(v??'').trim();if(required&&!s)fail(`${name}: campo obrigatório.`);if(s.length>10000)fail(`${name}: texto muito longo.`);return s;}
export function num(v,name,min=0,max=1e12,optional=false){if(optional&&(v===''||v==null))return null; if(v===''||v==null||!Number.isFinite(Number(v))||Number(v)<min||Number(v)>max)fail(`${name}: informe um número entre ${min} e ${max}.`);return Number(v);}
export function date(v,name,optional=false){if(optional&&!v)return '';if(!/^\d{4}-\d{2}-\d{2}$/.test(v||'')||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)fail(`${name}: data inválida.`);return v;}
export function choice(v,options,name){if(!options.includes(v))fail(`${name}: opção inválida.`);return v;}
export function hash(password){let salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(password,salt,64).toString('hex');}
export function verify(password,stored){const [salt,digest]=stored.split(':');return timingSafeEqual(scryptSync(password,salt,64),Buffer.from(digest,'hex'));}
export const money=v=>Math.round((Number(v)+Number.EPSILON)*100);
export function rules(v){const percent=num(v.percent,'Percentual',0,100), installments=num(v.installments,'Parcelas',1,120),payDay=num(v.payDay,'Dia de pagamento',1,31);if(!Number.isInteger(installments)||!Number.isInteger(payDay))fail('Parcelas e dia de pagamento devem ser inteiros.');return {percent,installments,payDay};}
export function schedule(value,rule,saleDate){date(saleDate,'Data da venda');rules(rule);const total=money(Number(value)*rule.percent/100),base=Math.floor(total/rule.installments);const [year,month]=saleDate.split('-').map(Number);return Array.from({length:rule.installments},(_,i)=>{const d=new Date(Date.UTC(year,month+i,1)),y=d.getUTCFullYear(),m=d.getUTCMonth(),last=new Date(Date.UTC(y,m+1,0)).getUTCDate();return {id:id(),number:i+1,amount:(i===rule.installments-1?total-base*i:base)/100,due:`${y}-${String(m+1).padStart(2,'0')}-${String(Math.min(rule.payDay,last)).padStart(2,'0')}`,received:0,receivedAt:'',history:[]};});}
export const paymentStatus=(due,receivedAt,now=today())=>receivedAt?'Pago':due<now?'Atrasado':'Aguardando';
export const commissionStatus=(p,now=today())=>money(p.received)>=money(p.amount)?'Paga':p.due<now?'Atrasada':'Aguardando';
export function landPrice(l){return l.condition==='Quitado'?l.price:l.balance==null?null:Number(l.premium)+Number(l.balance);}
export const duplicateKey=l=>[l.neighborhood,l.block,l.lot].map(s=>String(s||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()).join('|');
export function photos(v){if(!v)return [];if(!Array.isArray(v)||v.length>5)fail('Use no máximo cinco fotos.');return v.map(s=>{if(typeof s!=='string'||s.length>650000||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(s))fail('Foto inválida. Use JPG, PNG ou WebP de até 450 KB.');return s;});}
export function validateLand(v,db,user){const condition=choice(v.condition,['Quitado','Ágio'],'Condição');let l={neighborhood:text(v.neighborhood,'Bairro'),block:text(v.block,'Quadra'),lot:text(v.lot,'Lote'),area:num(v.area,'Área',0.01,1e9),condition,price:condition==='Quitado'?num(v.price,'Valor total',0.01):null,premium:condition==='Ágio'?num(v.premium,'Ágio',0):null,balance:condition==='Ágio'?num(v.balance,'Saldo devedor',0,1e12,true):null,balanceDate:date(v.balanceDate,'Referência do saldo',true),owner:text(v.owner,'Proprietário'),contact:text(v.contact,'Contato'),address:text(v.address,'Localização',false),description:text(v.description,'Descrição',false),notes:text(v.notes,'Observações',false),paymentTerms:text(v.paymentTerms,'Condições de pagamento',false),paymentOptions:Array.isArray(v.paymentOptions)?v.paymentOptions.filter(x=>['Entrada','Parcelamento','Financiamento','Permuta'].includes(x)):[],brokerId:user.role==='Corretor'?user.id:text(v.brokerId,'Corretor'),availability:choice(v.availability,['Disponível','Reservado','Vendido','Inativo'],'Disponibilidade'),photos:photos(v.photos)};if(!db.users.some(u=>u.id===l.brokerId&&u.active))fail('Corretor não encontrado.');if(l.balance!==null&&!l.balanceDate)fail('Informe a data de referência do saldo devedor.');return l;}
export function validateProduct(v,db){if(!db.developers.some(d=>d.id===v.developerId))fail('Selecione uma loteadora.');const mapUrl=text(v.mapUrl,'Link do mapa',false);if(mapUrl&&!/^https?:\/\//i.test(mapUrl))fail('O link do mapa deve começar com https://.');return {name:text(v.name,'Nome'),developerId:v.developerId,location:text(v.location,'Localização'),mapUrl,description:text(v.description,'Descrição',false),launch:!!v.launch,construction:!!v.construction,active:!!v.active,photos:photos(v.photos),...rules(v)};}
export function validateSale(v,db,user){const p=db.products.find(p=>p.id===v.productId&&p.active);if(!p)fail('Selecione um produto ativo.');const brokerId=user.role==='Corretor'?user.id:v.brokerId;if(!db.users.some(u=>u.id===brokerId&&u.active))fail('Corretor inválido.');const contract=choice(v.contract,['Aguardando assinatura','Assinado'],'Contrato'),saleDate=date(v.date,'Data da venda'),signedAt=date(v.signedAt,'Assinatura',true),paidAt=date(v.paidAt,'Pagamento',true);if(saleDate>today()||signedAt>today()||paidAt>today())fail('Datas de venda, assinatura e pagamento não podem estar no futuro.');if(contract==='Assinado'&&!signedAt)fail('Informe a data de assinatura.');const value=num(v.value,'Valor do lote',0.01),initial=num(v.initial,'Pagamento inicial',0,value);return {client:text(v.client,'Cliente'),contact:text(v.contact,'Contato'),productId:p.id,productName:p.name,developerId:p.developerId,brokerId,block:text(v.block,'Quadra'),lot:text(v.lot,'Lote'),date:saleDate,value,contract,signedAt:contract==='Assinado'?signedAt:'',initial,initialDue:date(v.initialDue,'Vencimento'),paidAt,notes:text(v.notes,'Observações',false),status:'Em andamento',rule:rules(p),commissions:schedule(value,rules(p),saleDate),history:[]};}
export function audit(user,action,details=''){return {id:id(),at:new Date().toISOString(),author:user.name,authorId:user.id,action,details};}
export function scoped(db,user){const sales=user.role==='Gestor'?db.sales:db.sales.filter(s=>s.brokerId===user.id);return {user:publicUser(user),users:db.users.map(u=>user.role==='Gestor'?publicUser(u):({id:u.id,name:u.name,role:u.role,active:u.active})),developers:db.developers,products:db.products,lands:db.lands,sales,rankingSales:db.sales.filter(s=>s.status!=='Cancelada'&&s.contract==='Assinado').map(s=>({brokerId:s.brokerId,date:s.date,value:s.value,productId:s.productId,developerId:s.developerId})),audit:user.role==='Gestor'?db.audit:[],demo:db.demo};}
export function publicUser(u){return {id:u.id,name:u.name,email:u.email,role:u.role,active:u.active};}
