import test from 'node:test';
import assert from 'node:assert/strict';
import {schedule,landPrice,commissionStatus,paymentStatus,scoped,today,validateLand,hash,date} from './domain.mjs';
import {execute} from './api.mjs';
function fixture(){return {demo:true,users:[{id:'g',name:'Gestora Teste',email:'g@test.local',role:'Gestor',active:true,password:hash('SenhaTeste12345')},{id:'b',name:'Corretor Teste',email:'b@test.local',role:'Corretor',active:true,password:hash('SenhaTeste12345')},{id:'b2',name:'Outro Corretor',email:'b2@test.local',role:'Corretor',active:true,password:hash('SenhaTeste12345')}],sessions:[],attempts:[],audit:[],developers:[],products:[],lands:[],sales:[]};}
const req=cookie=>({headers:{cookie},socket:{remoteAddress:'test'}});
async function login(db,email){let cookie='';await execute(db,req(),{setHeader:(k,v)=>{cookie=v.split(';')[0];}},{action:'login',email,password:'SenhaTeste12345'});return cookie;}
const run=(db,cookie,action,data)=>execute(db,req(cookie),{setHeader(){}},{action,data});
test('centavos exatos, mês seguinte, fevereiro bissexto e virada de ano',()=>{const ps=schedule(1000.01,{percent:3,installments:7,payDay:31},'2024-01-12');assert.equal(ps[0].due,'2024-02-29');assert.equal(ps[1].due,'2024-03-31');assert.equal(ps[2].due,'2024-04-30');assert.equal(Math.round(ps.reduce((a,p)=>a+p.amount,0)*100),3000);assert.equal(schedule(100,{percent:10,installments:1,payDay:31},'2025-12-31')[0].due,'2026-01-31');});
test('exemplo de março e status independentes do cliente',()=>{const p=schedule(200000,{percent:3,installments:3,payDay:20},'2026-03-12');assert.deepEqual(p.map(x=>x.due),['2026-04-20','2026-05-20','2026-06-20']);assert.equal(paymentStatus('2026-03-13','','2026-03-15'),'Atrasado');assert.equal(commissionStatus(p[0],'2026-03-15'),'Aguardando');assert.equal(commissionStatus({...p[0],received:100},'2026-04-21'),'Atrasada');});
test('ágio sem saldo não vira preço total e datas inválidas são rejeitadas',()=>{assert.equal(landPrice({condition:'Ágio',premium:50000,balance:null}),null);assert.equal(landPrice({condition:'Ágio',premium:50000,balance:130000}),180000);assert.throws(()=>date('2026-02-30','Data'));assert.throws(()=>date('2026-13-01','Data'));});
test('fluxo completo e permissões reais de servidor',async()=>{const db=fixture(),g=await login(db,'g@test.local'),b=await login(db,'b@test.local'),b2=await login(db,'b2@test.local');
await assert.rejects(run(db,b,'developer.save',{name:'Teste',contact:'123',percent:3,installments:3,payDay:20}),e=>e.status===403);
await run(db,g,'developer.save',{name:'Loteadora Teste',contact:'123',percent:3,installments:3,payDay:20});
await run(db,g,'product.save',{name:'Produto Teste',location:'Cuiabá',developerId:db.developers[0].id,percent:3,payDay:20,saleOptions:[{id:'three',entryMode:'with',entryInstallments:1,commissionMode:'fixed',commissionInstallments:3}],active:true});const p=db.products[0];
await run(db,b,'sale.create',{client:'Cliente Teste',contact:'123',productId:p.id,optionId:'three',leadSource:'Indicação',brokerId:'b2',block:'1',lot:'2',date:'2026-03-12',value:200000,contract:'Assinado',signedAt:'2026-03-12',initial:20000,initialDue:'2026-03-20',paidAt:'',notes:''});const s=db.sales[0];assert.equal(s.brokerId,'b');assert.equal(s.commissions[0].amount,2000);assert.equal(scoped(db,db.users[2]).sales.length,0);assert.equal(scoped(db,db.users[2]).rankingSales.length,1);assert.equal(JSON.stringify(scoped(db,db.users[1])).includes('password'),false);
await assert.rejects(run(db,b2,'sale.update',{id:s.id}),e=>e.status===404);
await assert.rejects(run(db,b,'commission.receive',{saleId:s.id,id:s.commissions[0].id,amount:2000,receivedAt:'2026-04-20'}),e=>e.status===403);
await run(db,g,'product.save',{...p,percent:8,saleOptions:[{id:'two',entryMode:'none',entryInstallments:0,commissionMode:'fixed',commissionInstallments:2}],payDay:10});assert.equal(s.rule.percent,3);assert.equal(s.commissions.length,3);
await run(db,g,'commission.receive',{saleId:s.id,id:s.commissions[0].id,amount:700,receivedAt:'2026-04-20'});assert.equal(s.commissions[0].received,700);await run(db,g,'commission.receive',{saleId:s.id,id:s.commissions[0].id,amount:1300,receivedAt:'2026-04-21'});assert.equal(commissionStatus(s.commissions[0]),'Paga');assert.equal(s.commissions[0].history.length,2);
await assert.rejects(run(db,g,'commission.receive',{saleId:s.id,id:s.commissions[0].id,amount:1,receivedAt:'2026-04-21'}));
await assert.rejects(run(db,b,'sale.cancel',{id:s.id,reason:'Teste'}),e=>e.status===403);await run(db,g,'sale.cancel',{id:s.id,reason:'Desistência'});assert.equal(scoped(db,db.users[0]).rankingSales.length,0);assert.equal(s.commissions[0].received,2000);assert.equal(s.status,'Cancelada');
const l={neighborhood:'Bairro teste',block:'10',lot:'4',area:300,condition:'Quitado',price:150000,owner:'Proprietário',contact:'123',availability:'Disponível',brokerId:'b'};
await run(db,b,'land.save',l);await run(db,b2,'land.activity',{id:db.lands[0].id,content:'Proposta recebida'});assert.equal(db.lands[0].history[0].author,'Outro Corretor');await assert.rejects(run(db,b2,'land.save',{...db.lands[0],price:160000}),e=>e.status===403);
let result=await run(db,b,'land.import',{rows:[l,{...l,lot:'5'},{...l,lot:'6',area:-1}],strategy:'skip'});assert.deepEqual([result.importResult.imported,result.importResult.skipped,result.importResult.errors.length],[1,1,1]);result=await run(db,b,'land.import',{rows:[{...l,price:170000}],strategy:'update'});assert.equal(result.importResult.updated,1);assert.equal(db.lands.find(x=>x.lot==='4').price,170000);assert.equal(db.lands.find(x=>x.lot==='4').history.length,3);
});
test('bloqueio de acesso desativado e limite de tentativas',async()=>{const db=fixture(),cookie=await login(db,'b@test.local');db.users[1].active=false;await assert.rejects(run(db,cookie,'state',{}),e=>e.status===401);for(let i=0;i<10;i++)await execute(db,req(),{setHeader(){}},{action:'login',email:'x@test',password:'errada'});const blocked=await execute(db,req(),{setHeader(){}},{action:'login',email:'g@test.local',password:'SenhaTeste12345'});assert.equal(blocked.status,429);});
