import {id,hash,schedule,audit} from './domain.mjs';
export function seed(){
const local=!process.env.VERCEL&&process.env.NODE_ENV!=='production',demo=local||process.env.DEMO_MODE==='true';
if(!demo&&(!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD||process.env.ADMIN_PASSWORD.length<12))throw Error('Configure ADMIN_EMAIL e ADMIN_PASSWORD (mínimo 12 caracteres).');
const users=[{id:'u1',name:'Marina Almeida',email:demo?'gestor@lotea.demo':process.env.ADMIN_EMAIL.toLowerCase(),role:'Gestor',active:true,password:hash(demo?'LoteaDemo2026!':process.env.ADMIN_PASSWORD)}];
const db={version:1,demo,users,lands:[],products:[],developers:[],sales:[],sessions:[],attempts:[],audit:[]};if(!demo){users[0].name=process.env.ADMIN_NAME||'Administrador';return db;}
users.push(...[['u2','Rafael Costa'],['u3','Camila Santos'],['u4','Lucas Ferreira']].map(([id,name])=>({id,name,email:id==='u2'?'corretor@lotea.demo':`${name.split(' ')[0].toLowerCase()}@lotea.demo`,role:'Corretor',active:true,password:hash('LoteaDemo2026!')})));
db.developers=[{id:'d1',name:'Urbaniza',contact:'(65) 3000-1000',percent:3,installments:3,payDay:20},{id:'d2',name:'Horizonte Urbanismo',contact:'(65) 3000-2000',percent:4,installments:4,payDay:15}];
db.products=[{id:'p1',name:'Jardim das Águas',developerId:'d1',location:'Cuiabá · MT',description:'Lotes residenciais com infraestrutura completa e áreas de convivência.',launch:true,construction:true,active:true,photos:[],mapUrl:'',percent:3,installments:3,payDay:20},{id:'p2',name:'Reserva do Parque',developerId:'d2',location:'Várzea Grande · MT',description:'Um novo bairro planejado, próximo à natureza e aos serviços da cidade.',launch:false,construction:true,active:true,photos:[],mapUrl:'',percent:4,installments:4,payDay:15},{id:'p3',name:'Alto do Cerrado',developerId:'d1',location:'Cuiabá · MT',description:'Empreendimento em lançamento, com lotes amplos e localização privilegiada.',launch:true,construction:false,active:true,photos:[],mapUrl:'',percent:3.5,installments:3,payDay:31}];
const now=new Date(),yr=now.getFullYear(),mo=now.getMonth();const dt=(offset,day)=>{let d=new Date(Date.UTC(yr,mo+offset,day));return d.toISOString().slice(0,10);};
const neighborhoods=['Jardim Itália','Santa Rosa','Jardim das Américas','Parque Cuiabá','Jardim Imperial','Boa Esperança'];
db.lands=neighborhoods.map((n,i)=>({id:'l'+i,neighborhood:n,block:String(8+i),lot:String(12+i),area:[360,450,300,420,500,250][i],condition:i%3===1?'Ágio':'Quitado',price:i%3===1?null:[198000,0,180000,235000,0,142000][i],premium:i%3===1?78000:null,balance:i===1?125000:null,balanceDate:i===1?dt(-1,15):'',owner:['Ana Ribeiro','Paulo Mendes','Helena Souza','João Nunes','Clara Rocha','Pedro Lima'][i],contact:'(65) 99900-000'+i,address:n+', Cuiabá – MT',description:'Terreno plano, com acesso por via asfaltada e serviços próximos.',notes:'Dados fictícios para demonstração.',paymentTerms:'Proprietário aberto a propostas. Valores sujeitos à confirmação.',paymentOptions:['Entrada','Financiamento'],brokerId:i%2?'u3':'u2',availability:['Disponível','Disponível','Reservado','Disponível','Disponível','Vendido'][i],photos:[],history:[audit(users[1],'Terreno cadastrado','Cadastro inicial do imóvel.')]}));
const names=['Fernanda Oliveira','Ricardo Martins','Juliana Mendes','Bruno Carvalho','Patrícia Gomes','Eduardo Rocha','Ana Beatriz','Marcos Silva','Letícia Dias','André Monteiro','Carolina Reis','Felipe Souza'];
db.sales=names.map((client,i)=>{const p=db.products[i%3],date=dt(i<4?0:i<8?-1:-2,i<4?Math.min(i+1,now.getDate()):8+i),rule={percent:p.percent,installments:p.installments,payDay:p.payDay},value=[240000,315000,198000,285000,360000,224000][i%6],commissions=schedule(value,rule,date);if(i>5){commissions[0].received=commissions[0].amount;commissions[0].receivedAt=commissions[0].due;commissions[0].history=[audit(users[0],'Recebimento registrado',String(commissions[0].amount))];}return {id:'s'+i,client,contact:'(65) 99900-100'+i,productId:p.id,productName:p.name,developerId:p.developerId,brokerId:['u2','u3','u4'][i%3],block:String(i+1),lot:String(i+10),date,value,contract:i===3?'Aguardando assinatura':'Assinado',signedAt:i===3?'':date,initial:20000,initialDue:i===3?dt(0,20):date,paidAt:i%4===0?'':date,notes:'Venda fictícia de demonstração.',status:i===11?'Cancelada':i===7?'Concluída':'Em andamento',rule,commissions,history:[audit(users[0],'Venda registrada')]};});
return db;
}
